LibrarySystem/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibrarySystem.Models;
using System.Data.SqlClient;

namespace LibrarySystem.Controllers
{
    public class MemberController : Controller
    {
        //
        // GET: /Member/
        [HttpGet]
        public ActionResult MemberEntry()
        {
            return View();
        }
        [HttpPost]
        public ActionResult MemberEntry(Member m)
        {
            Member md = new Member();
            m.M_ID = m.EMAIL.Split('@')[0];
            md.AddMember(m);
            return View(m);
        }
        [HttpGet]
        public ActionResult AllMemberSearch()
        {
            Member obj = new Member();
          List<Member>  ml=obj.AllMembers();
            return View(ml);
        }
        [HttpGet]
        public ActionResult search()
        {
            return View();
        }
        [HttpPost]
        public ActionResult search(string genderrb, string typedd)
        {
            Member md = new Member();
            List<Member> list1 = md.searchresult(genderrb, typedd);
            return View(list1);
        }

     
    }
}

LibrarySystem/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using LibrarySystem.Models;

namespace LibrarySystem.Controllers
{
    public class UserController : Controller
    {
        public static string con1 = "Data Source=DESKTOP-N4791LV;Initial Catalog=LibDB;Integrated Security=True";
        SqlConnection con = new SqlConnection(con1);
        [HttpGet]
        public ActionResult Signup()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Signup(User u1)
        {
            u1.save(u1);
            return RedirectToAction("Login");
        }
        [HttpGet]
        public ActionResult Login()
        {
            if (Session["uid"]!=null&&Session["name"]!=null)
            {
                return RedirectToAction("HomePage");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Login(User u2)
        {

            con.Open();
            string q = "select * from User1 where UID='" + u2.uid + "' and Password='" + u2.password + "'";
            SqlCommand cmd = new SqlCommand(q, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            sdr.Read();
            if (sdr.HasRows)
            {
                Session["uid"] = sdr["UID"].ToString();
                Session["name"] = sdr["Name"].ToString();
            }
            sdr.Close();
            con.Close();
            return RedirectToAction("WellCome");
        }
        [HttpGet]
        public ActionResult HomePage()
        {
            if (Session["uid"]!=null&&Session["name"]!=null)
            {

                return View();
            }

            return RedirectToAction("Signup");
        }
        [HttpGet]
        public ActionResult WellCome()
        {

            return View();
        }
    }
}

LibrarySystem/Views/Shared/LayoutView.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Library System By Mudassar Ali</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <script src="~/js/jquery-1.4.1.min.js"></script>
    <script src="~/js/menu.js"></script>
    <script src="~/js/slideshow.js"></script>
    <script src="~/js/cufon-yui.js"></script>
    <script src="~/js/Arial.font.js"></script>
<script type="text/javascript">Cufon.replace('h1,h2,h3,h4,h5,#menu,.blog-date');</script>
    <script src="~/js/fancyzoom.min.js"></script>
<script type="text/javascript" charset="utf-8">
$(document).ready(function () {
    $('div.photo a').fancyZoom({
        directory: 'images/zoom',
        scaleImg: true,
        closeOnClick: true
    });
});
</script>
    <link href="~/css/main.css" rel="stylesheet" />
</head>
<body>
<!-- START PAGE SOURCE -->
<div id="bg">
  <div class="wrap">
    <h1>Library System</h1>
    <div id="mainmenu">
      <ul id="menu">
        <li>@Html.ActionLink("Home","HomePage","User")</li>
        <li>@Html.ActionLink("Show All Books","ShowBook","Book")</li>
          <li>@Html.ActionLink("ABC","IssueBookForm","Book")</li>
        <li>@Html.ActionLink("Member Entry","MemberEntry","Member")</li>
        <li>@Html.ActionLink("Display All Member","AllMemberSearch","Member")</li>
        <li>@Html.ActionLink("Member Search","search","Member")</li>
          <li>@Html.ActionLink("Issue Book Form","IssueBook","Book")</li>
      </ul>
    </div>
    <div id="pitch">
      <div id="slideshow">
        <div class="active"> <img src="~/images/pitch/pitch1.jpg" />
          <div class="overlay transparent">
            <h2>Library Management System</h2>
            
          </div>
          <p class="arrow"><a href="#"></a></p>
        </div>
        <div> <img src="~/images/pitch/pitch2.jpg" alt="" />
          <div class="overlay transparent">
            <h2>BIIT Library System</h2>
          </div>
          <p class="arrow"><a href="#"></a></p>
        </div>
        <div> <img src="~/images/pitch/pitch3.jpg" />
          <div class="overlay transparent">
            <h2>Mudassar Ali</h2>
          </div>
          <p class="arrow"><a href="#"></a></p>
        </div>
      </div>
    </div>
    <div id="main">
        @RenderBody()
  </div>
  <div id="footer">
    <div id="footerbg">
      <div class="wrap">
        <p id="copy">Copyright &copy; 2010 <a href="#">Domain Name</a> - All Rights Reserved</p>
        <p id="footer_menu"><a href="http://all-free-download.com/free-website-templates/">Free CSS Templates</a> by <a href="http://www.solucija.com">Solucija</a></p>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>
<!-- END PAGE SOURCE -->
<div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div></body>
</html>