LibrarySystem/Models/ImageTest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LibrarySystem.Models
{
    public class ImageTest
    {
        public string user { get; set; }
        public string type { get; set; }
        public byte[] img { get; set;}
        
    }
}

LibrarySystem/Controllers/ImageTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data.SqlClient;

namespace LibrarySystem.Controllers
{
    public class ImageTestController : Controller
    {

        static string str="Data Source=DESKTOP-N4791LV;Initial Catalog=LibDB;Integrated Security=True";
        SqlConnection con=new SqlConnection(str);
        [HttpGet]
        public ActionResult Images()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Images(string Usertb,HttpPostedFileBase postedFile)
        {
            byte[] bytes;
            BinaryReader br = new BinaryReader(postedFile.InputStream);
           bytes= br.ReadBytes(postedFile.ContentLength);
            string contenttype = postedFile.ContentType;

            con.Open();

            string q = "insert into ImageTest values (@un,@img,@typ)";
            SqlCommand cmd = new SqlCommand(q, con);
            cmd.Parameters.AddWithValue("@un",Usertb);
            cmd.Parameters.AddWithValue("@img", bytes);
            cmd.Parameters.AddWithValue("@typ", contenttype);

            cmd.ExecuteNonQuery();
            con.Close();
            return View();
        }

    }
}

LibrarySystem/Views/ImageTest/Images.cshtml
@{
    Layout = null;
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Images</title>
</head>
<body>
 <h2>Image Test</h2>   
    @using (Html.BeginForm("Images", "ImageTest", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <b>User</b>@Html.TextBox("Usertb")
        <br />
        <b>Choose Image</b><input type="file" name="postedFile" />
        <br/>

        <input type="submit" value="submit" />
    }
</body>
</html>